# Update the workflow to ensure tabulate is installed
cat > .github/workflows/python-test.yml << 'EOF'
name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest
        pip install tabulate  # Ensure tabulate is installed

    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short
